use_frameworks!

target 'MAGDebugKit_Example' do

  pod 'MAGDebugKit', :path => '../'
  pod 'CocoaAsyncSocket', '~> 7.6'
  pod 'CocoaLumberjack', '~> 3.5'
  pod 'libextobjc', '~> 0.4'

  target 'MAGDebugKit_Tests' do
    inherit! :search_paths
  end
  
end
